### ISSUE TITLE
SelfControl starting outside schedule

### ISSUE THREAD

**Issue by j-krl** [Pandoks/hammer-control#11]
Just had SelfControl auto start at 7:55am on Tuesday when my schedule is set like this:

```
{
  "sunday": [],
  "monday": [
    {
      "start": "09:00",
      "end": "17:00",
      "blocklist": ".../blacklist.selfcontrol"
    }
  ],
  "tuesday": [
    {
      "start": "09:00",
      "end": "17:00",
      "blocklist": ".../blacklist.selfcontrol"
    }
],
  "wednesday": [
    {
      "start": "09:00",
      "end": "17:00",
      "blocklist": ".../blacklist.selfcontrol"
    }
],
  "thursday": [
    {
      "start": "09:00",
      "end": "17:00",
      "blocklist": ".../blacklist.selfcontrol"
    }
  ],
  "friday": [
    {
      "start": "09:00",
      "end": "17:00",
      "blocklist": ".../blacklist.selfcontrol"
    }
],
  "saturday": []
}
```

Some kind of bug?

**Comment by j-krl** [comment]
Looks like SelfControl is slated to end at 3pm even though I have 17:00 listed in the schedule

<img width="427" alt="Screenshot 2024-04-23 at 7 59 03 AM" src="https://github.com/Pandoks/hammer-control/assets/63491353/c1f431b8-14ab-47d4-8d22-02de33ffef2b">

**Comment by Pandoks** [comment]
Yea that's not supposed to happen :(.

Can you give me more information?

- Did your time zone change? Do you have internet connection?
- Did this happen when you restart your laptop?
- Did this happen when you woke your laptop from sleep?
- Did you sleep or turn off your laptop in the middle of a SelfControl session the day before or days before?

**Comment by j-krl** [comment]
> Can you give me more information?

I adjusted the `schedule.json` file to be 2 hours ahead of what it was previously, and that gets me my desired settings. So your program is reading the time as being 2 hours before my system time.

> Did your time zone change? Do you have internet connection?

I'm in Mountain Daylight Savings Time

> Did this happen when you restart your laptop?

This doesn't fix anything

> Did this happen when you woke your laptop from sleep?
> Did you sleep or turn off your laptop in the middle of a SelfControl session the day before or days before?

I let my laptop sleep every day when I stop using, so pretty tough to say if that's related. I doubt it though because restarting changes nothing.

Not totally sure what other info I can provide!

**Comment by Pandoks** [comment]
Thanks so much for the info!

For your time zone, is it set to automatically detect in settings or do you have it set manually?

Also how long was it working before this happened?

**Comment by j-krl** [comment]
The time is auto set.

I really don't know. Yesterday is the first time I noticed but it may have been happening for weeks.

**Comment by Pandoks** [comment]
> The time is auto set.
> 
> I really don't know. Yesterday is the first time I noticed but it may have been happening for weeks.

- Are you connected to internet? 
- Are you in a different location than the actual timezone? 
- Are you using a VPN?

**Comment by j-krl** [comment]
Well it started working as expected today, and my guess is it was related to a VPN I was using. I didn't think that would have an effect because with the VPN turned on I still have the same system time. Didn't cross my mind until you mentioned it. Thanks for the help!

**Comment by Pandoks** [comment]
> Well it started working as expected today, and my guess is it was related to a VPN I was using. I didn't think that would have an effect because with the VPN turned on I still have the same system time. Didn't cross my mind until you mentioned it. Thanks for the help!

What do you use your VPN for? The script checks for you location and time through the internet so that it can bypass people changing their system's time.

I'll try to figure out a way to make it work with a VPN though.
